config/routes.rb
Itswebsite2::Application.routes.draw do
  get "home/index"
  post "home/contact_mail", as: :contact_mail
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attachement.rb
# == Schema Information
#
# Table name: attachements
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  showcase_id        :integer
#

class Attachement < ActiveRecord::Base
  belongs_to :showcase
  has_attached_file :image, :styles => { :original => '400x400>' }, :default_url => "/images/:style/image-missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/partener.rb
# == Schema Information
#
# Table name: parteners
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  link              :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

class Partener < ActiveRecord::Base
  has_attached_file :logo, :styles => { :original => '100x30>' }, :default_url => "/images/:style/logo-missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :logo
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id          :integer          not null, primary key
#  pagename    :string(255)
#  title       :string(255)
#  keyword     :string(255)
#  description :text
#  author      :string(255)
#  headhtml    :text
#  bodyhtml    :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Setting < ActiveRecord::Base
end

app/models/showcase.rb
# == Schema Information
#
# Table name: showcases
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  subtitle             :string(255)
#  link                 :string(255)
#  description          :string(255)
#  short_description    :string(255)
#  sctype               :integer
#  created_at           :datetime
#  updated_at           :datetime
#  fontimg_file_name    :string(255)
#  fontimg_content_type :string(255)
#  fontimg_file_size    :integer
#  fontimg_updated_at   :datetime
#

class Showcase < ActiveRecord::Base
    extend Enumerize
    has_attached_file :fontimg, :styles => { :original => '580x370#' }, :default_url => "/images/:style/fontimg-missing.png"
    has_attached_file :detail_img, :styles => { :website => '854x532#', app: '323x570#' }, :default_url => "/images/:style/detail_img-missing.png"
    validates_attachment_content_type :fontimg, :content_type => /\Aimage\/.*\Z/
    validates_attachment_content_type :detail_img, :content_type => /\Aimage\/.*\Z/
    has_many :showcases, dependent: :destroy
    validates_attachment_presence :fontimg
    validates_attachment_size :fontimg, less_than: 5.megabytes
    validates_attachment_size :detail_img, less_than: 5.megabytes
    validates_attachment_presence :detail_img

    enumerize :sctype, in: {:app => 1, :website => 2, :iframe => 3, :other => 4}
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  position           :string(255)
#  email              :string(255)
#  phone              :string(255)
#  description        :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  photo_file_name    :string(255)
#  photo_content_type :string(255)
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

class Team < ActiveRecord::Base
    has_attached_file :photo, :styles => { :original => '400x400>' }, :default_url => "/images/:style/photo-missing.png"
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
    validates_attachment_presence :photo
    validates_attachment_size :photo, less_than: 5.megabytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @parteners = Partener.all
    @showcases = Showcase.order(:ordernum)
    @team = Team.all
  end

  def contact_mail
    ContactMailer.contact_mail(params).deliver
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_app_partiel.html.erb
<div class="modal-app">
    <div class="row">

        <div class="col-md-6 preview" data-dismiss="modal">
            <div style="position: relative; margin: 10px;">
                <div class="wireframe"></div>
                <div class="screen" style="background-image: url(<%= sc.detail_img.url(:app) %>);"></div>
                <img src="<%= asset_path "iphone.png", type: :image %>" style="visibility: hidden;">
            </div>
        </div>

        <div class="col-md-6 infos">
            <div class="center-verticaly">
                <p class="title" data-dismiss="modal"><%= sc.title %></p>
                <p class="subtitle" data-dismiss="modal"><%= sc.subtitle %></p>
                <p class="description" data-dismiss="modal"><%= sc.description %></p>
                <p class="link">
                <% if not sc.link.nil? and sc.link.length > 5 %>
                    <a href="<%= sc.link %>" type="button" class="apple-store-btn">
                        <img src="<%= asset_path "app_market/apple.png", type: :image %>" alt="apple store download" width="150" />
                    </a>
                <% end %>
                <% if not sc.link2.nil? and sc.link2.length > 5 %>
                    <a href="<%= sc.link2 %>" type="button" class="android-market-btn">
                        <img src="<%= asset_path "app_market/android.png", type: :image %>" alt="android market download" width="145" />
                    </a>
                <% end %>
                </p>
            </div>
        </div>

    </div>
</div>

app/views/home/_contact.html.erb
<div id="contact" class="section footer-padding">
  <div class="container no-bottom">
    <div class="content">
      <div class="text-center">
        <h2 class="title">联系我们</h2>
      </div>
      <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
        <div class="col-md-8 col-sm-8 col-xs-12">
          <p class="description">
            </p>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
      </div>
    </div>
  </div>
  <div id="map-canvas"></div>
  <div class="container no-pad">
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <p class="icon-description">
            <span class="icon-wrapper">
              <span class="circle"><i class="ion-location"></i></span>
            </span>
            北京市海淀区静淑苑2号清华科技园-创业广场601A
          </p>
          <p class="icon-description">
            <span class="icon-wrapper">
              <span class="circle"><i class="ion-ios7-telephone"></i></span>
            </span>
            010-8236-3288
          </p>
          <p class="icon-description">
            <span class="icon-wrapper">
              <span class="circle"><i class="ion-ios7-email"></i></span>
            </span>
             contact@itsium.cn
          </p>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <p class="description">
          请使用下方表格与我们联系，您可以写下您的建议或服务需求，我们会尽快与您联系。
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <h2>请您留言</h2>

    <div class="content" id="mailform">
      <form role="form" method="post" action="<%= contact_mail_url %>">
        <div class="form-group">
          <label for="exampleInputName"><i class="icon-tag"></i></label>
          <input name="name" type="text" class="form-control" id="exampleInputName" placeholder="姓名" required>
          <div class="clearfix"></div>
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1"><i class="icon-inbox"></i></label>
          <input name="mail" type="email" class="form-control" id="exampleInputEmail1" placeholder="电子信箱" required>
          <div class="clearfix"></div>
        </div>
        <div class="form-group textarea">
          <label for="exampleInputMessage"><i class="icon-pencil"></i></label>
          <textarea name="body" rows="6" class="form-control" id="exampleInputMessage" placeholder="您的留言" required></textarea>
          <div class="clearfix"></div>
        </div>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <button type="submit" class="btn color">发送留言</button>
      </form>
    </div>
  </div>
</div><!-- /.container -->

app/views/home/_footer.html.erb
<div id="footer" class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
        <p><a href="http://www.miitbeian.gov.cn/">京ICP备13043450</a> &copy; 2014, Made by <a href="#">Itsium Inc.</a>  <script type="text/javascript">
  var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
  document.write(unescape("%3Cspan id='cnzz_stat_icon_1252946212'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1252946212' type='text/javascript'%3E%3C/script%3E"));
  </script> </p>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="">
        <p class="social-media">
          <a href="http://www.weibo.com/ITSIUM" target="_black" data-toggle="tooltip" title="weibo"><i class="fa fa-weibo"></i></a>
          <a href="#" data-toggle="tooltip" title="renren"><i class="fa fa-renren"></i></a>
          <a href="#" data-toggle="tooltip" title="applestore"><i class="fa fa-apple"></i></a>
          <a href="#" data-toggle="tooltip" title="androidmarcket"><i class="fa fa-android"></i></a>
          <a href="http://www.pinterest.com/itsium/" data-toggle="tooltip" title="pinterest"><i class="fa fa-pinterest"></i></a>
        </p>
     </div>
    </div>
  </div>
</div>

app/views/home/_main_section.html.erb
   <!-- Home Section -->
<div id="home" class="section macbook">
  <div class="parallax main-background"><%= image_tag "deep-blue3.jpg" %></div>
  <div class="row">
    <div class="col-md-1 col-sm-1 col-xs-12 empty"></div>
    <div class="col-md-10 col-sm-10 col-xs-12 full">
      <div class="logo"><%= image_tag "logo.png" %></div>
      <h1 class="welcome">
         意得捷优<br/><span>跨平台移动技术开发与策略咨询</span>
      </h1>
      <div class="macbook-preview">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <%= image_tag "macbookAir.png", class: "outline" %>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @showcases.each_with_index do | sc, i | %>
              <div class="item <%= "active" if i == 0 %>">
                <%= image_tag sc.fontimg.url(:original), class: "shot" %>
              </div>
            <% end -%>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <i class="fa fa-angle-left"></i>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </div>

    </div>
    <div class="col-md-1 col-sm-1 col-xs-12 empty"></div>
  </div>
</div><!-- /.container -->

app/views/home/_navbar.html.erb
<div id="navbar" class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand scroll" href="#home"><%= image_tag "logo2.png" %></i><span>    ITSIUM</span></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a class="scroll" href="#services">初识ITSIUM</a></li>
            <li><a class="scroll" href="#clients">合作伙伴</a></li>
            <li><a class="scroll" href="#portfolio">实例展示</a></li>
            <li><a class="scroll" href="#team">公司团队</a></li>
            <li><a class="scroll" href="#contact">联系我们</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/home/_other_partiel (copy).html.erb
aaa

app/views/home/_other_partiel.html.erb
aaa

app/views/home/_our_business.html.erb
<div class="modals">

  <div class="modal fade" id="modal_service_1" tabindex="-1" data-dismiss="modal" role="dialog">
    <div class="modal-dialog" data-dismiss="modal">
    <div class="modal-content">
    <div class="business-container">
      <%= image_tag asset_path "business/intro-01.jpg", type: :image %>
    </div></div></div>
  </div>
  <div class="modal fade" id="modal_service_2" tabindex="-1" data-dismiss="modal" role="dialog">
    <div class="modal-dialog modal-lg" data-dismiss="modal">
    <div class="modal-content">
    <div class="business-container">
      <%= image_tag asset_path "business/intro-02.jpg", type: :image %>
    </div></div></div>
  </div>
  <div class="modal fade" id="modal_service_3" tabindex="-1" data-dismiss="modal" role="dialog">
    <div class="modal-dialog" data-dismiss="modal">
    <div class="modal-content">
    <div class="business-container">
      <%= image_tag asset_path "business/intro-03.jpg", type: :image %>
    </div></div></div>
  </div>
  <div class="modal fade" id="modal_service_4" tabindex="-1" data-dismiss="modal" role="dialog">
    <div class="modal-dialog" data-dismiss="modal">
    <div class="modal-content">
    <div class="business-container">
      <%= image_tag asset_path "business/intro-04.jpg", type: :image %>
    </div></div></div>
  </div>

</div>

<div id="services" class="section gray">
  <div class="container">

    <div class="content">
      <div class="text-center">
        <h2 class="title">专业的跨平台移动服务</h2>
      </div>
      <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
        <div class="col-md-8 col-sm-8 col-xs-12">
          <p class="description">专注于企业的技术支持，让您驻足在高新技术的顶峰。 秉承高效服务，先进技术支持，让每个客户满意于我们的服务，得意于我们的技术，为您提供快捷优质的全新体验！真正做到你的想法，我实现！
            </p>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">

        <a data-toggle="modal" href="#modal_service_1">
          <div class="service">
            <div class="icon-wrapper">
              <span class="circle"><i class="ion-ios7-lightbulb"></i></span>
            </div>
            <h3>APP定制开发</h3>
            <p>我们拥有全球领先的跨平台APP开发技术以及多年的APP开发经验。以优秀的创意和高效的执行能力给客户带来最大的利益是我们的宗旨。</p>
          </div>
        </a>

        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">

        <a data-toggle="modal" href="#modal_service_2">
          <div class="service">
            <div class="icon-wrapper">
              <span class="circle"><i class="fa fa-rocket"></i></span>
            </div>
            <h3>微信公共平台定制开发</h3>
            <p>意得捷优为您提供最贴身的最时尚的微信公共平台定制服务，自主研发的HTML5+JS微网页开发技术给您的企业带来最有创意和最绚丽的微信公共平台应用。</p>
          </div>
        </a>

        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">

        <a data-toggle="modal" href="#modal_service_3">
          <div class="service">
            <div class="icon-wrapper">
              <span class="circle"><i class="ion-film-marker"></i></span>
            </div>
            <h3>技术咨询与技术培训</h3>
            <p>由来自于不同国籍的工程师组成的技术团队能给您的企业带来最专业的技术服务和解决方案。 </p>
          </div>
        </a>

        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">

        <a data-toggle="modal" href="#modal_service_4">
          <div class="service">
            <div class="icon-wrapper">
              <span class="circle"><i class="ion-thumbsup"></i></span>
            </div>
            <h3>新媒体营销</h3>
            <p>怎么让微信，微博，App这些新媒体工具给自己的企业带来最大的利益呢? 这就是我们的专业团队能帮助您解决的问题。</p>
          </div>
        </a>
        </div>
      </div>
    </div><!-- /.content -->
  </div>
</div>

<% content_for :bodyhtml do %>
<script>
<!--
$(document).on('show.bs.modal', '.modal', function () {

  var modal = $(this);

  modal.find('.modal-dialog').click(function() {
    modal.modal('hide');
  });
});
// -->
</script>
<% end %>

app/views/home/_page_settings.html.erb
<% @pagesettings = Setting.where(pagename: controller.action_name).first %>

<% content_for :title do %>
  <%= @pagesettings.title %>
<% end %>
<% content_for :headhtml do %>
  <%= @pagesettings.headhtml.html_safe %>
<% end %>
<% content_for :bodyhtml do %>
  <%= h @pagesettings.bodyhtml.html_safe %>
<% end %>
<% content_for :author do %>
  <%= @pagesettings.author %>
<% end %>
<% content_for :description do %>
  <%= @pagesettings.description %>
<% end %>

<% content_for :keyword do %>
  <%= @pagesettings.keyword %>
<% end %>

app/views/home/_partners.html.erb
<div id="clients" class="section dark">
     <div class="parallax"><!--<img src="/assets/partners-2.jpg">--></div>

     <div class="container">

       <div class="content">

         <div class="text-center">
           <h2 class="title"><%= t :partener %></h2><br>
         </div>

         <div class="row">

           <div class="col-md-2 col-sm-2 col-xs-12"></div>
           <div class="col-md-8 col-sm-8 col-xs-12">
             <p class="description"><%=t :partener_desc %>
             </p>
           </div>
           <div class="col-md-2 col-sm-2 col-xs-12"></div>

         </div>

       </div> <!-- /content -->

       <div id="partners-carousel" class="carousel slide" data-ride="carousel">

         <!-- Wrapper for slides -->
         <div class="carousel-inner">

          <% last = @parteners.length - 1 %>
          <% @parteners.each_with_index do | p, i | %>
             <% if ((i +1)  % 4) == 1 %>
              <div class="item <%= "active" if i == 0 %>">
                <ul class="row">
             <% end -%>
              <li class="col-md-3 col-sm-6 col-xs-12">
                <% if not p.link.nil? and p.link.length > 5 %>
                  <a href="<%= p.link %>" class="thumbnail partner-link" target="_blank">
                <% else %>
                  <a href="javascript:;" class="thumbnail partner-link">
                <% end %>
                  <div class="partner-image" style="background-image: url('<%= p.logo.url(:original) %>');">
                    <img src="<%= p.logo.url(:original) %>" alt="<%= p.name %>">
                  </div>
                 </a>
               </li>

            <% if ((i+1) % 4 )== 0 or i == last %>
                </ul>
              </div>
             <% end -%>
          <% end -%>
         </div>

         <!-- Controls -->
         <a id="partners-carousel-prev" class="left carousel-control" href="#partners-carousel" role="button" data-slide="prev">
           <i class="fa fa-angle-left"></i>
         </a>
         <a id="partners-carousel-next" class="right carousel-control" href="#partners-carousel" role="button" data-slide="next">
           <i class="fa fa-angle-right"></i>
         </a>

       </div>


     </div>
   </div>

<% content_for :bodyhtml do %>
<script>
<!--
$(document).ready(function() {

  var $carousel = $('#partners-carousel');

  $('#partners-carousel-prev').click(function() {
    $carousel.carousel('prev');
  });

  $('#partners-carousel-next').click(function() {
    $carousel.carousel('next');
  });

});
// -->
</script>
<% end %>

app/views/home/_portfolios.html.erb
<!-- All Page Modals -->
<div class="modals">

  <% @showcases.each_with_index do | sc, i | %>
      <div class="modal fade modal-portfolio" id="modal<%= (i+1)%>" tabindex="-1" data-dismiss="modal" role="dialog">
        <div class="modal-dialog modal-lg"><div class="modal-content">
          <%= render "#{sc.sctype}_partiel", sc: sc %>
        </div></div><!-- /.content -->
      </div><!-- /.modal -->
  <% end -%>
</div><!-- /.modals -->

<!-- All Font Showcase -->
<div id="portfolio" class="section gray">
  <div class="container">
    <div class="content">
      <div class="text-center">
        <h2 class="title"><%=t :portfolios %></h2>
      </div>
      <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
        <div class="col-md-8 col-sm-8 col-xs-12">
          <p class="description"><%=t :portfolios_desc %>
            </p>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
      </div>

    </div><!-- /.content -->

    <div id="grid" class="row masonry-grid effect-2">
     <% @showcases.each_with_index do | sc, i | %>
        <li class="col-md-4 col-sm-4 col-xs-12 item">
        <a data-toggle="modal" href="#modal<%= (i + 1) %>" class="image">
          <img src="<%= sc.fontimg.url(:original) %>" alt="<%= sc.title %>">
          <span class="overlay"><span class="valign"></span><i class="ion-ios7-search"></i></span>
        </a>
        <div class="description">
          <h2><%= sc.title %></h2>
          <p><%= sc.short_description %></p>
          <div class="clearfix"></div>
        </div>
        </li>
      <% end -%>

    </div>
  </div>

</div><!-- /.container -->

<% content_for :bodyhtml do %>
<script>
<!--
$(document).on('show.bs.modal', '.modal', function () {

  var modal = $(this);

  modal.find('.wrapper').click(function() {
    modal.modal('hide');
  });
});
// -->
</script>
<% end %>

app/views/home/_team.html.erb
<!-- Meet the Team Section -->
<div id="team" class="section dark">
  <div class="parallax"><%= image_tag "office.jpg" %></div>
  <div class="container">
    <div class="content">
      <div class="text-center">
        <h2 class="title"><%= t(:meet_the_team) %></h2>
      </div>
      <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
        <div class="col-md-8 col-sm-8 col-xs-12">
          <p class="description"><%=t :team_desc %>
            </p>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-12"></div>
      </div>

      <div class="row">

        <% @team.each do | member | %>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <div class="wrapper">
            <a href="#mailform" class="portrait-wrapper scroll">
              <img class="portrait" src="<%= member.photo.url(:original)%>">
              <span class="overlay"><span class="valign"></span><i class="ion-ios7-email"></i></span>
            </a>
            <div class="text-center">
              <h3><%= member.name %></h3>
              <p><%= member.position %></p>
            </div>
          </div>
        </div>
        <% end -%>
      </div>

    </div><!-- /.content -->
  </div>
</div>

app/views/home/_website_partiel.html.erb
<div class="modal-website">
    <div class="row">
        <div class="col-md-3 infos" data-dismiss="modal">
            <p class="title" data-dismiss="modal"><%= sc.title %></p>
            <p class="subtitle" data-dismiss="modal"><%= sc.subtitle %></p>
            <p class="description" data-dismiss="modal"><%= sc.description %></p>
            <p class="link">
            <% if not sc.link.nil? and sc.link.length > 5 %>
                <a href="<%= sc.link %>" type="button" class="btn btn-preview-link">实例链接</a>
            <% end %>
            </p>
        </div>
        <div class="col-md-9 preview" data-dismiss="modal">
            <div class="macbook"></div>
            <div class="screen" style="background-image: url(<%= sc.detail_img.url(:website) %>);"></div>
            <img src="<%= asset_path "macbook-modal.png", type: :image %>" style="visibility: hidden;">
        </div>
    </div>
</div>

app/views/home/index.html.erb
<%= render 'page_settings' %>
<%= render 'navbar' %>
<%= render 'main_section' %>
<%= render 'our_business' %>
<%= render 'partners' %>
<%= render 'portfolios' %>
<%= render 'team' %>
<%= render 'contact' %>
<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
 <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui">
    <meta name="description" content="<%= yield :description %>">
    <meta name="keywords" content="<%= yield :keyword %>" />
    <meta name="author" content="<%= yield :author %>">

    <title><%= yield :title %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">

    <!--[if lt IE 9]>
      <script src="/assets/respond.min.js"></script>
    <![endif]-->

    <!-- Montserrat Sans -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Montserrat:400, 700' rel='stylesheet' type='text/css'>-->
    <!-- Lato Font -->
    <!--<link href='http://fonts.googleapis.com/css?family=Lato:300,700' rel='stylesheet' type='text/css'>-->

    <%= yield :headhtml %>

  </head>

  <body class="blue">
    <%= yield %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <script src="http://webapi.amap.com/maps?v=1.2&key=2a27af19d2466d650d065db5423efd74" type="text/javascript"></script>

      <%= yield :bodyhtml %>
    <svg id="svg-image-blur">
        <filter id="blur-effect">
            <feGaussianBlur stdDeviation="3" />
        </filter>
    </svg>
  </body>



</html>